### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by AI-Study-Han** [StriveZs/ALPS#2]
[2024-08-21 16:51:48 Test](main.py 281): INFO Loaded pretrained k-means model from ./raw_img/k_means.pkl...
Traceback (most recent call last):
  File "main.py", line 414, in <module>
    main()
  File "main.py", line 401, in main
    online_k_means_clustering_test()
  File "main.py", line 282, in online_k_means_clustering_test
    logger.info('kmeans cluster centers:' + str(kmeans.cluster_centers_))
AttributeError: 'MiniBatchKMeans' object has no attribute 'cluster_centers_'
这是什么问题啊？

**Comment by AI-Study-Han** [comment]
自己文件路径没配置好
